apiVersion: v1
kind: Service
metadata:
  name: bookflow-backend
  namespace: bookflow
spec:
  type: NodePort
  selector:
    app: bookflow-backend
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30085
