@BookFlow_Api_HostAddress = http://localhost:5161

### Health
GET {{BookFlow_Api_HostAddress}}/health

### Get books page 1
GET {{BookFlow_Api_HostAddress}}/api/books?page=1&pageSize=5&search=

### Create book
POST {{BookFlow_Api_HostAddress}}/api/books
Content-Type: application/json

{
  "title": "Clean Code",
  "author": "Robert C. Martin",
  "genre": "Software",
  "publishedYear": 2008,
  "availableCopies": 3
}

### Get book by id
GET {{BookFlow_Api_HostAddress}}/api/books/REPLACE_ID

### Update book
PUT {{BookFlow_Api_HostAddress}}/api/books/REPLACE_ID
Content-Type: application/json

{
  "title": "Clean Code - Updated",
  "author": "Robert C. Martin",
  "genre": "Software Engineering",
  "publishedYear": 2008,
  "availableCopies": 5
}

### Delete book
DELETE {{BookFlow_Api_HostAddress}}/api/books/REPLACE_ID